DOCUMENTATION: https://annoying-api.srnyx.com/wiki/File-objects


# Whether the default color files (blue, brown, gray, green, red) should be generated
default-colors: true

# The amount of damage to deal to the player if they step on a colored block
# Put "kill" (or any string) to completely kill the player
damage: "kill"

rotate:
  # The time in seconds between each rotation
  time: 60

  # The time in seconds the players are given before the color is changed
  # This HAS to be less than the time above (unless time is 0, then it doesn't matter)
  delay: 5

  sounds:
    delay: # SOUND
      # Whether a sound should be played every DELAY second
      enabled: true
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.5
      pitch: 0.5
      category: MASTER
    set: # SOUND
      # Whether a sound should be played when the color is set
      enabled: true
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.5
      pitch: 1
      category: MASTER
