name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${mainPackage}.${name}
version: ${version}
api-version: 1.13

commands:
  colorreload:
    description: Reload the plugin
    aliases:
      - criticalcolorsreload
    permission: criticalcolors.reload
  color:
    description: Change the color players can't touch
    aliases:
      - criticalcolors
    permission: criticalcolors.color
  colorrotate:
    description: Toggle the automatic color change
    aliases:
      - criticalcolorsrotate
    permission: criticalcolors.rotate
  colorbar:
    description: Toggle the color bossbar
    aliases:
      - colorbossbar
      - criticalcolorsbar
      - criticalcolorsbossbar
    permission: criticalcolors.bar

permissions:
  criticalcolors.reload:
    description: Allows access to use /colorreload
  criticalcolors.color:
    description: Allows access to use /color
  criticalcolors.rotate:
    description: Allows access to use /colorrotate
  criticalcolors.bar:
    description: Allows access to use /colorbar
